name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: check lint
        run: make lint
      - name: check imports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          DIFF=$(goimports -l .)
          if [ ! -z "$DIFF" ]; then
            echo "failed to check goimports. diff: [$DIFF]"
            exit 1
          fi
